### ISSUE TITLE
API

### ISSUE THREAD

**Issue by samuel-l-schmidt** [isaiah658/isaiah658.github.io#5]
Hey, 

really impressive project. Are you still working on it?
I am writing a python script, where I want to call your website... I was thinking about an API, do you see any way to implement something like that? Or do you have a better idea? :) 

Thanks

**Comment by isaiah658** [comment]
> 
> 
> Hey,
> 
> really impressive project. Are you still working on it?
> I am writing a python script, where I want to call your website... I was thinking about an API, do you see any way to implement something like that? Or do you have a better idea? :)
> 
> Thanks

I'm really sorry for the late response. As far as I know, nothing is broken (but I don't test the project often). I'll fix any bugs people find, but I don't plan on adding in new features. Also the code pretty messy. I'm not a programmer, and this was my first project after not coding for several years, so I made some very bad code organization decisions. I tried my best to go back and fix it, but due to the shear number of options the user can select, it's always going to feel messy.

As for an API, I'm not exactly sure what you mean. My visualizer works entirely in the web browser. It's just a static web page. No dynamic content. You can clone/download the project and open the index.html file in a supported web brower and it works. I would recommend downloading a copy and implementing it into your project. You could have your own local copy and modify it to do what you need. It could be bundled with the script if you plan on distributing it to others.

**Comment by isaiah658** [comment]
If you still have questions, feel free to reopen this.
